### ISSUE TITLE
압축이 잘못된거 같네요..

### ISSUE THREAD

**Issue by monoshop** [kimsQ/rb_module_member#7]
압축파일 밑에 
rb_module_member-develop 폴더가 존재하기 때문에 설치시 오류 뜹니다.

폴더 빼서 재 압축 후 설치하면 괜찮구요..

압축패키징을 다시 해서 올리셔야 할거같은데요

----------------

지금 보니 압축파일이 download 버튼 클릭시 파일하고 본문에 있는 파일하고 틀리군요..

**Comment by gitaeks** [comment]
@monoshop 님,  Rb2설치형 패키지는 아래의 링크에서 다운받으셔야 합니다.
저장소 오른쪽 하단에 있는 다운로드는 단순히 브랜치단위로 소스코드 전체로 ZIP으로 내려받는 기능으로 설치패키지화가 고려 되지 않았습니다.

https://github.com/kimsQ/rb_module_member/releases
